### ISSUE TITLE
No such file or directory: '/Users/julian/.not_token'

### ISSUE THREAD

**Issue by twayz** [sixninetynine/not#11]
Hi,

I kept getting this error below after running not-setup. However, after manually creating an empty file at '/Users/julian/.not_token' the error disappeared. Just thought i'd give you a heads up. Thank you!

➜  ~  not-setup
No token! run not-setup! [Errno 2] No such file or directory: '/Users/julian/.not_token'
Traceback (most recent call last):
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/bin/not-setup", line 9, in <module>
    load_entry_point('not==1.2', 'console_scripts', 'not-setup')()
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/**init**.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2672, in load_entry_point
    return ep.load()
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2345, in load
    return self.resolve()
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2351, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/notpy/oauth.py", line 6, in <module>
    import config
  File "/Users/julian/.anyenv/envs/pyenv/versions/2.7.9/lib/python2.7/site-packages/notpy/config.py", line 18, in <module>
    TOKEN = token
NameError: name 'token' is not defined

**Comment by lorencarvalho** [comment]
hi!

thanks for checking out `not` -- this issue was a result of me being a terrible developer and not testing anything :grimacing:

this commit https://github.com/sixninetynine/not/commit/e84aa9f2d5b6a211a64a432b1c229f1be06307d5 fixes it in a sane way imo

thanks again, enjoy :+1:
