### ISSUE TITLE
failures result in lost messages

### ISSUE THREAD

**Issue by lorencarvalho** [sixninetynine/not#3]
mn: ~ → not mobile_training
Traceback (most recent call last):
  File "/usr/local/bin/not", line 8, in <module>
    load_entry_point('not==1.0', 'console_scripts', 'not')()
  File "build/bdist.macosx-10.9-intel/egg/notpy/cmd.py", line 58, in cli
    These are often useful for test harnesses, administrative tools, and
  File "build/bdist.macosx-10.9-intel/egg/notpy/**init**.py", line 72, in save
  File "build/bdist.macosx-10.9-intel/egg/evernote/api/client.py", line 138, in delegate_method
  File "build/bdist.macosx-10.9-intel/egg/evernote/edam/notestore/NoteStore.py", line 4601, in createNote
  File "build/bdist.macosx-10.9-intel/egg/evernote/edam/notestore/NoteStore.py", line 4625, in recv_createNote
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=11, parameter="The entity name must immediately follow the '&' in the entity reference.")

**Comment by lorencarvalho** [comment]
fixed https://github.com/sixninetynine/not/commit/64553c08d23a7a3ebc14ac163d3469b7be3c4df2
